// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT8x77ANGxqUY1z26PcaaB46dZMDUotUc',
    appId: '1:784072938244:web:21452ef8089679747b7651',
    messagingSenderId: '784072938244',
    projectId: 'teamtaskapp-10698',
    authDomain: 'teamtaskapp-10698.firebaseapp.com',
    storageBucket: 'teamtaskapp-10698.firebasestorage.app',
    measurementId: 'G-9EGTWRS4JR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWIxlmoiBj_U9KMoDwdBVa7hwA7iOD3pg',
    appId: '1:784072938244:android:54c48c811dbd1a3a7b7651',
    messagingSenderId: '784072938244',
    projectId: 'teamtaskapp-10698',
    storageBucket: 'teamtaskapp-10698.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT8x77ANGxqUY1z26PcaaB46dZMDUotUc',
    appId: '1:784072938244:web:ad10aa22cc12bbf47b7651',
    messagingSenderId: '784072938244',
    projectId: 'teamtaskapp-10698',
    authDomain: 'teamtaskapp-10698.firebaseapp.com',
    storageBucket: 'teamtaskapp-10698.firebasestorage.app',
    measurementId: 'G-TZMPX73TWW',
  );
}
